### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by matthewmueller** [dokku/dokku-rethinkdb#1]
how would you open the admin panel in this case?

**Comment by matthewmueller** [comment]
^ oh, is that what the `expose` and `unexpose` are meant to do?

**Comment by josegonzalez** [comment]
Yep though they don't yet work.

On Wednesday, September 2, 2015, Matthew Mueller <notifications@github.com>
wrote:

> ^ oh, is that what the expose and unexpose are meant to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku/dokku-rethinkdb/issues/1#issuecomment-137268253>
> .
>


-- 
Jose Diaz
Operations Engineer @ SeatGeek

**Comment by josegonzalez** [comment]
This isn't quite well documented yet, but it works. Here is what you can do:

```shell
dokku rethinkdb:expose <name>
```

Which will have the following output:

```shell
# !     Service is already started
#-----> Service test exposed on port(s) 31756 911 14073
```

The last port there is the port that has the rabbitmq administration panel. In the future, we'll have some nicer output explaining which port is what...

**Comment by jimthedev** [comment]
@josegonzalez is there any way to have a password on the rethinkdb admin page while still having the port exposed?

**Comment by jimthedev** [comment]
Not quite, all that is required is to set the initial password in the users table for the admin password. More here: http://rethinkdb.com/docs/security/#the-admin-account

**Comment by josegonzalez** [comment]
Can you open a new issue for this as a feature request?
