### ISSUE TITLE
Add option to lock down admin interface

### ISSUE THREAD

**Issue by jimthedev** [dokku/dokku-rethinkdb#30]
As mentioned in #1 you can expose the RethinkDB admin port with `dokku rethinkdb:expose <name>`. The last port in the list is the admin ip address. The problem is that by default there is no password on this interface, leaving the database vulnerable.

It would be fantastic to add a feature that would set the initial password in the users table for the admin password and print it to the screen. More here: http://rethinkdb.com/docs/security/#the-admin-account

An alternative subcommand implementation would be to prompt the user for a password. I don't really mind what it is called but I was thinking the subcommand could look something like:

```
dokku rethinkdb:protect <name>
```

**Comment by josegonzalez** [comment]
What is the proper write call, and is there a way to do that from the provided docker image?

**Comment by aleclarson** [comment]
Using `--initial-password auto` on startup will do what you want.

Could that be baked into `dokku-rethinkdb`?

**Comment by buckle2000** [comment]
Just do the following:
1. only expose to localhost:<port>
2. connect via SSH, set up port forwarding
3. open `localhsot:<port>` in local browser

This method works better than setting up a password.

**Comment by josegonzalez** [comment]
Going to close this for now. The proper way to expose a web ui for a service plugin is now documented [here](https://github.com/dokku/service-proxy), and may in the future become a command within each plugin.
