### ISSUE TITLE
Cannot delete linked service => Not linked to app

### ISSUE THREAD

**Issue by aleclarson** [dokku/dokku-rethinkdb#34]
```sh
$ dokku rethinkdb:destroy foo
Cannot delete linked service

$ dokku rethinkdb:unlink foo foo
Not linked to app foo
```

The service and its linked app have the same name. It won't let me unlink the app, thus I can't destroy the service. Any ideas why this is happening, or how to fix?

**Comment by aleclarson** [comment]
The workaround is to do `dokku apps:destroy foo`

**Comment by josegonzalez** [comment]
Without seeing the output of `dokku rethinkdb:info SERVICE` and the trace output of the commands you ran, I can't really help debug. Sorry.

**Comment by aleclarson** [comment]
I'll let you know if I run into it again. 👍

**Comment by aleclarson** [comment]
```sh
vagrant@dokku:~$ dokku rethinkdb:link foo my-app
/var/lib/dokku/plugins/available/docker-options/functions: line 89: /home/dokku/my-app/DOCKER_OPTIONS_DEPLOY: Permission denied
```

When that happens, `rethinkdb:unlink foo my-app` fails.

**Comment by aleclarson** [comment]
`dokku rethinkdb:info foo`

```
=====> Container Information
       Config dir:          /var/lib/dokku/services/rethinkdb/foo/config
       Data dir:            /var/lib/dokku/services/rethinkdb/foo/data
       Dsn:                 rethinkdb://dokku-rethinkdb-foo:28015/foo
       Exposed ports:       -                        
       Id:                  054bb4d3e2d7e9cc1f06ba407262757a74e041dfd9d438f24db8405f8da67faa
       Internal ip:         172.17.0.3               
       Links:               my-app                    
       Service root:        /var/lib/dokku/services/rethinkdb/foo
       Status:              running                  
       Version:             rethinkdb:2.3.4  
```

**Comment by josegonzalez** [comment]
`ls -lah /home/dokku/my-app/`

The permissions on all the files in there are probably root or something, you'll need to do:

```
chown -R dokku:dokku /home/dokku/my-app/
```

**Comment by aleclarson** [comment]
Did this happen during `dokku plugin:install`?

**Comment by josegonzalez** [comment]
The files are created by the dokku user - even when you run the `dokku` binary as root, since we change user - so I think you actually are screwing with your file permissions somewhere else.
