### ISSUE TITLE
Connecting to dokku-rethinkdb

### ISSUE THREAD

**Issue by aleclarson** [dokku/dokku-rethinkdb#35]
Using `dokku config:get my-app RETHINKDB_URL`
returns `rethinkdb://dokku-rethinkdb-foo:28015/my-app`
but how should I pass that to the driver?

The following code fails to connect:

```js
const rethinkdb = require('rethinkdb')
const r = rethinkdb({
  host: 'rethinkdb://dokku-rethinkdb-foo/my-app',
})
```

Here's the error:
```
Failed to connect to rethinkdb://dokku-rethinkdb-foo/my-app:28015
```

I also tried `host: 'rethinkdb://dokku-rethinkdb-foo:28015/my-app'` but it did not work.

**Comment by josegonzalez** [comment]
If your driver doesn't understand how to read a [DSN](https://en.wikipedia.org/wiki/Data_source_name), then you'll need to parse the DSN and set the properties manually.

**Comment by aleclarson** [comment]
Surprisingly, neither the official Javascript driver, nor [neumino/rethinkdbdash](https://github.com/neumino/rethinkdbdash) support such a thing.

**Comment by aleclarson** [comment]
It doesn't seem like my app container has access to rethinkdb.

Here's what I did:

```sh
dokku apps:create my-app
dokku rethinkdb:create foo
dokku rethinkdb:link foo my-app
dokku enter my-app
node
> var socket = net.connect('rethinkdb://dokku-rethinkdb-foo:28015/my-app');
> Error: connect ENOENT rethinkdb://dokku-rethinkdb-foo:28015/my-app
```

Is there anything I can do to test this connection outside of `node`?

**Comment by aleclarson** [comment]
Using `curl http://172.17.0.2:8080`, I've confirmed that my container can access rethinkdb.

I'm still interested in why the DSN can't be connected to.

Is it reliable to hard code the internal IP into my application?

**Comment by aleclarson** [comment]
Found a way to convert `dokku-rethinkdb-foo` into `172.17.0.2`:

```js
dns.lookup('dokku-rethinkdb-foo', function(error, host) {
  console.log(host); // '172.17.0.2'
})
```

I guess that will have to do for now.

**Comment by aleclarson** [comment]
Hmm, still cannot connect.

```js
var socket = net.connect('http://172.17.0.2:28015/my-app');
// Error: connect ENOENT http://172.17.0.2:28015/my-app
```

**Comment by aleclarson** [comment]
Okay, I can get it connected to `http://172.17.0.2:28015` like so:
```js
var socket = net.connect('28015', '172.17.0.2');
```
Now is it necessary to connect to `/my-app`, or am I allowed to leave that out?

**Comment by aleclarson** [comment]
Hmm, the RethinkDB driver seems to be working, despite not connecting to `http://172.17.0.2:28015/my-app`.

So I guess it's not required? Wasted a lot of time thinking it was required. 😢

**Comment by josegonzalez** [comment]
`my-app` would be your "database" or whatever rethinkdb calls that.

**Comment by aleclarson** [comment]
Oh okay. It doesn't look like it's working correctly.

Using `dbList` in the web UI says there's no `my-app` database.

```js
r.dbList.run()
// [
//   "rethinkdb" ,
//   "test"
// ]
```

**Comment by aleclarson** [comment]
@josegonzalez Have you looked into why the `foo` database is not being created as expected?

**Comment by josegonzalez** [comment]
Guess we don't create the database. You can file an issue for that, seems we can do it via rql as shown [here](https://www.rethinkdb.com/api/javascript/#db_create).

I likely won't work on the issue since I don't use rethinkdb, but if you'd like to contribute that enhancement, that would be wonderful.
