### ISSUE TITLE
Specify ports used to expose the internal ports

### ISSUE THREAD

**Issue by aleclarson** [dokku/dokku-rethinkdb#38]
Can I choose which ports are used to expose 28015, 29015, and 8080?

`dokku rethinkdb:expose` uses random ports, where I would prefer specifying the ports because I have to update the firewall whenever I want to access the RethinkDB web UI.

**Comment by josegonzalez** [comment]
Try:

```
dokku rethinkdb:help expose
```

**Comment by aleclarson** [comment]
@josegonzalez Am I forced to expose all 3 ports?

**Comment by josegonzalez** [comment]
Yes you are.
