### ISSUE TITLE
Swap Memory

### ISSUE THREAD

**Issue by heks** [dokku/dokku-rethinkdb#39]
I am running this plugin on my server and I keep getting this warning/error on my rethinkdb logs:

"Some RethinkDB data on this server has been placed into swap memory. This may impact performance."

rethinkdb cache-size=100mb (automatic)

I have a 2GB server, anyone know whats causing this ? Bad configuration, time for upgrade?

**Comment by josegonzalez** [comment]
You need more memory, thats it.

**Comment by aleclarson** [comment]
@heks You might find the "Cache size" section [on this page](https://www.rethinkdb.com/docs/memory-usage) useful.
