### ISSUE TITLE
Invalid database name

### ISSUE THREAD

**Issue by buckle2000** [dokku/dokku-rethinkdb#40]
The default database name is identical to the app name. However, database name in RethinkDB must Use `[A-Za-z0-9_]+` only.

So if you have an app named `xxx-yyy`, the program will break because `xxx-yyy` is an invalid db name.

**Comment by josegonzalez** [comment]
There is a similar problem here for mysql/mongo. I think I'm going to implement a regex to limit the characters to the ones you've mentioned above.

This _might_ affect users for other plugins, but they can checkout the appropriate version of their plugin, export the data, recreate under a new name, and re-update.

- dokku/dokku-mysql#47
- dokku/dokku-mongo#86

**Comment by josegonzalez** [comment]
This issue was moved to dokku/dokku-redis#99
