### ISSUE TITLE
How to only expose some but not all ports?

### ISSUE THREAD

**Issue by buckle2000** [dokku/dokku-rethinkdb#41]
In file `/var/lib/dokku/services/rethinkdb/db/PORT`, I must specify 3 ports. However, I only want to export one of these 3 port. What should I do?

**Comment by aleclarson** [comment]
You're forced to expose all 3 right now ([see here](https://github.com/dokku/dokku-rethinkdb/issues/38#issuecomment-332031402)). I'd bet it's not too difficult to add that, though.

I'm currently using port whitelisting via my hosting provider.

**Comment by josegonzalez** [comment]
You can't expose only a certain port for a service.
